### ISSUE TITLE
Google.Protobuf package version incompatibility

### ISSUE THREAD

**Issue by ArtemiiUstiukhinFortum** [signalfx/splunk-otel-dotnet#526]
**Describe the bug**
OpenTelemetry.AutoInstrumentation.Loader.Loader throws an exception `Could not load file or assembly 'Google.Protobuf, Version=3.22.5.0` when instrumented .NET App contains different version of the Google.Protobuf package.

**To Reproduce**
1. Create .NET application with the **Google.Protobuf** package version **3.19.1**.
2. Create a Docker container with the .NET application, utilizing the Splunk Distribution of OpenTelemetry for .NET (See example [here](https://github.com/splunk/observability-content-contrib/tree/main/integration-examples/splunk-otel-dotnet-docker))
3. Set the **OTEL_LOG_LEVEL** environment variable to **debug** before starting your instrumented application.
4. Run Dockerized application and generate some activity.
5. Collect the debug logs. The instrumentation saves its logs in the following locations: Linux: /var/log/opentelemetry/dotnet

**Expected behavior**
Splunk Distribution of OpenTelemetry .NET is running without errors.

**Runtime environment:**
- Instrumentation mode: in Docker container (See example [here](https://github.com/splunk/observability-content-contrib/tree/main/integration-examples/splunk-otel-dotnet-docker))
- Tracer version: v1.6.0
- .NET version: net8.0
- Host platform: k8s (EKS)
- OS: Linux (amd64)
- Docker base image: mcr.microsoft.com/dotnet/sdk:8.0-jammy

OTEL ENV:
```
- name: SPLUNK_OTEL_AGENT
  valueFrom:
    fieldRef:
      fieldPath: status.hostIP
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: "http://$(SPLUNK_OTEL_AGENT):4318"
- name: OTEL_SERVICE_NAME
  value: "app-name"
- name: OTEL_RESOURCE_ATTRIBUTES
  value: "deployment.environment=${ENV}"
- name: OTEL_DOTNET_AUTO_HOME
  value: "$HOME/.splunk-otel-dotnet"
- name: OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED
  value: "false"
```

**Solution**
A simple `Google.Protobuf` upgrade to `Version=3.22.5.0` fixes the issue. However it would be nice to know about incompatible packages in advance, because the only way to figure out the issue was to set the **OTEL_LOG_LEVEL** environment variable to **debug** and manually inspect the logs.
